# Project Name
TARGET = HelloAudioDaisyPod

# Sources
CPP_SOURCES = HelloAudioDaisyPod.cpp

# Flags
LDFLAGS = -u _printf_float

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
